version: '3.9'

services:
    minio:
        container_name: minio
        image: minio/minio
        command: minio server /data --console-address ":9001"
        ports:
            - 9000:9000
            - 9001:9001
        volumes:
            - minio_data:/data
        environment:
            MINIO_ACCESS_KEY: ${ACCESS_KEY}
            MINIO_SECRET_KEY: ${SECRET_KEY}
        networks:
            - webnet
        logging:
            driver: 'json-file'
            options:
                max-size: '8m'
                max-file: '10'
        restart: always

volumes:
    minio_data:

networks:
    webnet:
        name: webnet
        driver: bridge
